### ISSUE TITLE
Getting error when running  OpenMindsAI

### ISSUE THREAD

**Issue by remoteassist** [Hassassistant/OpenMindsAI#1]
I am not able to run the addon, also the screenshot look different from the one shown on the github, is there anything I can check?

```
2023-04-27 17:23:51.221 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/openmindsai/sensor.py", line 69, in async_ask
    response = await self._hass.async_add_executor_job(ask, self._session_cookie, self._model, new_query)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openmindsai/sensor.py", line 31, in ask
    response_message = response_json[0]["response"]
KeyError: 0
```
![image](https://user-images.githubusercontent.com/115590002/234995343-055511b2-c344-4aff-b5ab-68c9e79e3610.png)

**Comment by Hassassistant** [comment]
Thanks for the feedback. I'll check this out later today if I get a moment.
Also that is the correct session cookie you've got there.

**Comment by rquiroz2** [comment]
I had the same issue, but I found that I had the sensor model name wrong.

If you copied the lines from the README to create the model, your sensor should read:

Sensor:
  - platform: openmindsai
    ...
    model: ""gpt4hassio" 

and not

Sensor:
  - platform: openmindsai
    ...
    model: "gpt4"

**Comment by Failure404** [comment]
I've made sure that I used the same model name in my sensor config I gave the model initially in the Minds DB editor, but I also get the very same error.
In the Minds DB editor I've used:
CREATE  MODEL mindsdb.gpt4myname
Then in the sensor config I've used:
model: "gpt4myname"
That is how I understood the instructions.

**Comment by rquiroz2** [comment]
maybe your cookies?
I had to play around a lot to get the full cookies right. if you hover over the cookies field, you can see what the cookies should be.

Mine started with a ".e" and had two long parts seperated with a "-". Sometimes copying the field gave me the first half only, or without the "." in the beginning. There's a space at the end of the cookie that you have to delete too.

**Comment by remoteassist** [comment]
Thanks @rquiroz2 that was the problem. In the configuration.yaml , the instruction in the README is incorrect. 
![image](https://user-images.githubusercontent.com/115590002/235217834-61f4c281-6df1-457f-a919-b108ae8841a6.png)
![image](https://user-images.githubusercontent.com/115590002/235218152-dbc3e38e-4646-48ba-a159-a8c982dad88d.png)

**Comment by Hassassistant** [comment]
thanks for pointing this out guys. i was in a mad rush to get this live.

**Comment by Hassassistant** [comment]
Typo my end.
